version: '3.7'

services:

  database:
    image: postgres
    environment:
      - POSTGRES_DB=cloud_project
      - POSTGRES_NAME=cloud_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=petar
    expose:
      - "5342"
    volumes:
      - cloud_proj_database:/var/lib/postgresql/data

  web:
    restart: "on-failure:5"
    build: ..
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=#django-insecure-8rd#hy-4_=3t+!7&9$$0u$$(-e&hq8orxn5o%ft^l$$gtu2x)vqye
      - DB_NAME=cloud_project
      - DB_USER=postgres
      - DB_PASS=petar
      - DB_HOST=database
      - DB_PORT=5432
    depends_on:
      - database

volumes:
  cloud_proj_database:
